
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 02 18:15:23 VET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Eq = 15;
  public static final int Suma = 28;
  public static final int Numero = 26;
  public static final int Dif = 9;
  public static final int Palabra = 3;
  public static final int Uni = 8;
  public static final int numero = 2;
  public static final int Mayor = 17;
  public static final int And = 12;
  public static final int ParentI = 22;
  public static final int Fecha = 5;
  public static final int Int = 11;
  public static final int Coma = 24;
  public static final int ParentD = 23;
  public static final int Or = 13;
  public static final int Not = 14;
  public static final int EOF = 0;
  public static final int Proc = 10;
  public static final int Resta = 29;
  public static final int Pro = 7;
  public static final int error = 1;
  public static final int Punto = 25;
  public static final int Menor = 18;
  public static final int Menorq = 21;
  public static final int Caracter = 4;
  public static final int Multi = 27;
  public static final int Mayorq = 19;
  public static final int PuntoComa = 20;
  public static final int Diferente = 16;
  public static final int Sel = 6;
}

